### ISSUE TITLE
make fails with cpu only and gpu

### ISSUE THREAD

**Issue by nddk** [JonathanRaiman/Dali#8]
Hi, really helpful if you could shed some light on this: 

I'm trying to build on Ubuntu 14.04:

without cuda I get the following errors:

In file included from /usr/bin/../lib/gcc/x86_64-linux-gnu/4.8/../../../../include/c++/4.8/vector:60:
/usr/bin/../lib/gcc/x86_64-linux-gnu/4.8/../../../../include/c++/4.8/bits/stl_algobase.h:739:11: error: overload
      resolution selected deleted operator '='
        *__first = __value;
        ~~~~~~~~ ^ ~~~~~~~
/usr/bin/../lib/gcc/x86_64-linux-gnu/4.8/../../../../include/c++/4.8/bits/stl_algobase.h:786:23: note: in
      instantiation of function template specialization 'std::__fill_n_a<std::atomic<int> *, unsigned long,
      std::atomic<int> >' requested here
      return _OI(std::__fill_n_a(std::__niter_base(__first), __n, __value));
                      ^
/usr/bin/../lib/gcc/x86_64-linux-gnu/4.8/../../../../include/c++/4.8/bits/stl_uninitialized.h:515:9: note: in
      instantiation of function template specialization 'std::fill_n<std::atomic<int> *, unsigned long,
      std::atomic<int> >' requested here
          std::fill_n(__first, __n, _ValueType());
               ^
/usr/bin/../lib/gcc/x86_64-linux-gnu/4.8/../../../../include/c++/4.8/bits/stl_uninitialized.h:544:2: note: in
      instantiation of function template specialization
      'std::__uninitialized_default_n_1<true>::__uninit_default_n<std::atomic<int> *, unsigned long>' requested
      here
        __uninit_default_n(__first, __n);
        ^
/usr/bin/../lib/gcc/x86_64-linux-gnu/4.8/../../../../include/c++/4.8/bits/stl_uninitialized.h:605:12: note: in
      instantiation of function template specialization 'std::__uninitialized_default_n<std::atomic<int> *,
      unsigned long>' requested here
    { std::__uninitialized_default_n(__first, __n); }
           ^
/usr/bin/../lib/gcc/x86_64-linux-gnu/4.8/../../../../include/c++/4.8/bits/stl_vector.h:1224:7: note: in
      instantiation of function template specialization 'std::__uninitialized_default_n_a<std::atomic<int> *,
      unsigned long, std::atomic<int> >' requested here
        std::__uninitialized_default_n_a(this->_M_impl._M_start, __n, 
             ^
/usr/bin/../lib/gcc/x86_64-linux-gnu/4.8/../../../../include/c++/4.8/bits/stl_vector.h:271:9: note: in
      instantiation of member function 'std::vector<std::atomic<int>, std::allocator<std::atomic<int> >
      >::_M_default_initialize' requested here
      { _M_default_initialize(__n); }
        ^
/media/xwd/hgst2tb/rnn-parser/working-lstm/Dali/dali/utils/scoring_utils.cpp:7:98: note: in instantiation of
      member function 'std::vector<std::atomic<int>, std::allocator<std::atomic<int> > >::vector' requested here
    ConfusionMatrix::ConfusionMatrix(int classes, const vector<string>& _names) : names(_names), totals(c...
                                                                                                 ^
/usr/bin/../lib/gcc/x86_64-linux-gnu/4.8/../../../../include/c++/4.8/atomic:602:15: note: candidate function has
      been explicitly deleted
      atomic& operator=(const atomic&) = delete;
              ^
/usr/bin/../lib/gcc/x86_64-linux-gnu/4.8/../../../../include/c++/4.8/bits/atomic_base.h:360:22: note: candidate
      function has been explicitly deleted
      __atomic_base& operator=(const __atomic_base&) = delete;
                     ^
/usr/bin/../lib/gcc/x86_64-linux-gnu/4.8/../../../../include/c++/4.8/atomic:603:15: note: candidate function has
      been explicitly deleted
      atomic& operator=(const atomic&) volatile = delete;
              ^
/usr/bin/../lib/gcc/x86_64-linux-gnu/4.8/../../../../include/c++/4.8/bits/atomic_base.h:361:22: note: candidate
      function has been explicitly deleted
      __atomic_base& operator=(const __atomic_base&) volatile = delete;
                     ^
/usr/bin/../lib/gcc/x86_64-linux-gnu/4.8/../../../../include/c++/4.8/bits/atomic_base.h:373:7: note: candidate
      function
      operator=(__int_type __i) noexcept
      ^
/usr/bin/../lib/gcc/x86_64-linux-gnu/4.8/../../../../include/c++/4.8/bits/atomic_base.h:380:7: note: candidate
      function
      operator=(__int_type __i) volatile noexcept
      ^
1 error generated.

And with cuda support I get: 

Linking CXX executable ../../../third_party/json11/bin/tests
/usr/lib/llvm-3.6/bin/../lib/clang/3.6.0/include/adxintrin.h(55): error: identifier "__builtin_ia32_addcarry_u32" is undefined

/usr/lib/llvm-3.6/bin/../lib/clang/3.6.0/include/adxintrin.h(63): error: identifier "__builtin_ia32_addcarry_u64" is undefined

/usr/lib/llvm-3.6/bin/../lib/clang/3.6.0/include/adxintrin.h(71): error: identifier "__builtin_ia32_subborrow_u32" is undefined

/usr/lib/llvm-3.6/bin/../lib/clang/3.6.0/include/adxintrin.h(79): error: identifier "__builtin_ia32_subborrow_u64" is undefined

[ 29%] Built target tests
4 errors detected in the compilation of "/tmp/tmpxft_00007297_00000000-7_ThrustAllocator.cpp1.ii".
CMake Error at dali_cuda_generated_ThrustAllocator.cu.o.cmake:264 (message):
  Error generating file
  /media/xwd/hgst2tb/rnn-parser/working-lstm/Dali/build/dali/CMakeFiles/dali_cuda.dir/math/./dali_cuda_generated_ThrustAllocator.cu.o


make[2]: *** [dali/CMakeFiles/dali_cuda.dir/math/./dali_cuda_generated_ThrustAllocator.cu.o] Error 1
make[2]: *** Waiting for unfinished jobs....
/usr/lib/llvm-3.6/bin/../lib/clang/3.6.0/include/adxintrin.h(55): error: identifier "__builtin_ia32_addcarry_u32" is undefined

/usr/lib/llvm-3.6/bin/../lib/clang/3.6.0/include/adxintrin.h(63): error: identifier "__builtin_ia32_addcarry_u64" is undefined

/usr/lib/llvm-3.6/bin/../lib/clang/3.6.0/include/adxintrin.h(71): error: identifier "__builtin_ia32_subborrow_u32" is undefined

/usr/lib/llvm-3.6/bin/../lib/clang/3.6.0/include/adxintrin.h(79): error: identifier "__builtin_ia32_subborrow_u64" is undefined

4 errors detected in the compilation of "/tmp/tmpxft_000072b9_00000000-7_Weights.cu.cpp.cpp1.ii".
CMake Error at dali_cuda_generated_Weights.cu.cpp.cu.o.cmake:264 (message):
  Error generating file
  /media/xwd/hgst2tb/rnn-parser/working-lstm/Dali/build/dali/CMakeFiles/dali_cuda.dir/__/build/cuda_files/tensor/./dali_cuda_generated_Weights.cu.cpp.cu.o


make[2]: *** [dali/CMakeFiles/dali_cuda.dir/__/build/cuda_files/tensor/./dali_cuda_generated_Weights.cu.cpp.cu.o] Error 1
make[1]: *** [dali/CMakeFiles/dali_cuda.dir/all] Error 2
make: *** [all] Error 2


Any help is highly appreciated!

**Comment by nivwusquorum** [comment]
I believe you need GNU g++ >= 4.9.2.

**Comment by nivwusquorum** [comment]
Also I have not really tested the build on Ubuntu that well. I know it works on Fedora 21 and Mac OS.

**Comment by nivwusquorum** [comment]
Now we have a pre-relase of prebuilt binaries. Highly encourage giving it a try!
